---

- name: Create YUM repo file
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: "{{ waagent_epel_yumrepo_url }}"
    gpgkey:  "{{ waagent_epel_yumrepo_gpgkey }}"
    params: "{{ waagent_epel_yumrepo_params }}"
  when: waagent_epel_install
  tags:
    - waagent_pkg

- name: Install WALinuxAgent package
  package:
    name: "{{ waagent_pkg }}"
  notify:
    - Restart waagent service
  tags:
    - waagent_pkg

- name: Configure waagent
  template:
    src: waagent.conf.j2
    dest: "{{ waagent_config_file }}"
  notify:
    - Restart waagent service
  tags:
    - waagent_config

- name: Enable waagent service
  service:
    name: "{{ waagent_service }}"
    enabled: yes
  tags:
    - waagent_service

- name: Start waagent service
  service:
    name: "{{ waagent_service }}"
    state: started
  register: waagent_service_started
  tags:
    - waagent_service
